### ISSUE TITLE
Data discrepancy

### ISSUE THREAD

**Issue by HashBasher** [openfootball/world-cup#31]
I see some data discrepancy between the number of goals on the 2014 datasets vs. this website: 

https://www.sportskeeda.com/football/fifa-world-cup-2014-top-scorers-and-assist-providers

E.g. Neymar has 2 goals according to the dataset, but 4 on the website.

**Comment by geraldb** [comment]
Thanks for (double) checking.  If you're interested in helping out / contributing, you are more than welcome. Maybe you can check the brazllian matches to see a difference? PS: Please post your comments to the forum / mailing list <http://groups.google.com/group/sportdb>.
